name: Unit tests

on:
    pull_request:
        types: [opened, synchronize, reopened]
    push:
        branches:
        - main
        - master
    
jobs:
  unit-test:
    name: Tests and Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - run: npx tsc --noEmit
      
